class Constants {
  val SPARK_MASTER_PROP = "spark.master"
  val SPARK_APP_NAME_PROP = "spark.app.name"
  val SPARK_SCHEDULER_MODE_PROP = "spark.scheduler.mode"
  val SPARK_CASSANDRA_CONNECTION_TIMEOUT_MS_PROP = "spark.cassandra.connection.timeout_ms"
  val SPARK_CASSANDRA_FETCH_SIZE_IN_ROWS_PROP = "spark.cassandra.input.fetch.size_in_rows"
  val SPARK_CASSANDRA_KEEP_ALIVE_MS_PROP = "spark.cassandra.connection.keep_alive_ms"
  val SPARK_CASSANDRA_CONNS_PER_EXECUTOR_MAX_PROP = "spark.cassandra.connection.connections_per_executor_max"
  val SPARK_CASSANDRA_CONN_COMPRESSION_TYPE_PROP = "spark.cassandra.connection.compression"
  val SPARK_CASSANDRA_OUTPUT_IGNORENULLS_PROP = "spark.cassandra.output.ignoreNulls"
  val SPARK_CASSANDRA_OUTPUT_CONCURRENT_WRITES_PROP = "spark.cassandra.output.concurrent.writes"
  val SPARK_CASSANDRA_OUTPUT_THROUGHPUT_MB_SEC_PROP = "spark.cassandra.output.throughput_mb_per_sec"
  val SPARK_CASSANDRA_OUTPUT_BATCH_SIZE_BYTES_PROP = "spark.cassandra.output.batch.size.bytes"
  val SPARK_CASSANDRA_OUTPUT_BATCH_SIZE_ROWS_PROP = "spark.cassandra.output.batch.size.rows"
  val SPARK_CASSANDRA_OUTPUT_BATCH_WAIT_MS_PROP = "spark.cassandra.output.batch.wait.ms"
  val SPARK_CASSANDRA_OUTPUT_CONSISTENCY_LEVEL_PROP = "spark.cassandra.output.consistency.level"
  val SPARK_CASSANDRA_OUTPUT_METRICS_PROP = "spark.cassandra.output.metrics"
}
